#!/bin/bash
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success2.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success3.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success4.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success5.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success6.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success7.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success8.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success9.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success10.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes2.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes3.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes4.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes5.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes6.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes7.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes8.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes9.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes10.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss2.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss3.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
