#!/bin/bash
sudo echo 'uploading files to s3 bucket' > /tmp/success1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success2.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success3.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success4.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success5.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success6.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success7.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success8.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success9.txt
sudo echo 'uploading files to s3 bucket' > /tmp/success10.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes2.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes3.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes4.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes5.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes6.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes7.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes8.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes9.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succes10.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss1.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss2.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss3.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss14.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss15.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss16.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss17.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss18.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss19.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss100.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss4.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss5.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss5.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss6.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss7.txt
sudo echo 'uploading files to s3 bucket' > /tmp/succss8.txt
sudo echo 'Several residential localities experienced power failure for several hours on Wednesday, when heavy rains pounded the city. Residents in several areas said they experienced intermittent power cuts ranging from two to three hours.The officials of the Tamil Nadu General and Distribution Corporation (Tangedco) said the power cuts were part of precautionary steps taken to avoid any electrical accidents due to waterlogging of roads, trees falling on transformers and snapping of overhead power lines due to gusty winds.Power supply was switched off in parts of south Chennai, covering Nanganallur, Velachery, Madipakkam, Keelkattalai, Pallikaranai, Medavakkam and Tambaram. These areas are predominantly served by overhead power lines and the local EB officials went for a power shutdown from the morning.In several streets of Velachery, covering Ram Nagar, Vijaya Nagar, Balamurugan Nagar, Annai Indira Nagar and Bethel Avenue, power supply was stopped due to waterlogged roads. Also several parts of ECR and OMR, includingaipakkam, went without power supply.K. Ramaswamy, a resident of Maheshwari Avenue in Ullagaram-Puzhithivakkam, complained that the power supply which went off at 2 p.m. had not been restored for over four hours.A senior official of south Chennai said local officials from different sections were deputed to restore power supply even in those roads where rain water stagnated after taking necessary safety precautions.In central and north parts of the city, power supply was switched off by the electricity officials due to waterlogging and tripping of transformers.A senior official of Tangedco said power supply in some core parts of the city was cut off mainly due to waterlogging. It was disrupted in NSC Bose Road, Anna Pillai Street, Anderson Street, Edappalayam, Cooks Road and Decaster Road in Pulianthope; Sivarajapuram of Choolai section; Baraccah Road in Nammalwarpet; Divan Bashyam Street in Saidapet; and Chari street and Lotus Colony in T. Nagar.In Madhanankuppam, coming under Red Hills section, power supply ws ' > /tmp/succss9.txt
sudo echo 'Several residential localities experienced power failure for several hours on Wednesday, when heavy rains pounded the city. Residents in several areas said they experienced intermittent power cuts ranging from two to three hours.The officials of the Tamil Nadu General and Distribution Corporation (Tangedco) said the power cuts were part of precautionary steps taken to avoid any electrical accidents due to waterlogging of roads, trees falling on transformers and snapping of overhead power lines due to gusty winds.Power supply was switched off in parts of south Chennai, covering Nanganallur, Velachery, Madipakkam, Keelkattalai, Pallikaranai, Medavakkam and Tambaram. These areas are predominantly served by overhead power lines and the local EB officials went for a power shutdown from the morning.In several streets of Velachery, covering Ram Nagar, Vijaya Nagar, Balamurugan Nagar, Annai Indira Nagar and Bethel Avenue, power supply was stopped due to waterlogged roads. Also several parts of ECR and OMR, includingaipakkam, went without power supply.K. Ramaswamy, a resident of Maheshwari Avenue in Ullagaram-Puzhithivakkam, complained that the power supply which went off at 2 p.m. had not been restored for over four hours.A senior official of south Chennai said local officials from different sections were deputed to restore power supply even in those roads where rain water stagnated after taking necessary safety precautions.In central and north parts of the city, power supply was switched off by the electricity officials due to waterlogging and tripping of transformers.A senior official of Tangedco said power supply in some core parts of the city was cut off mainly due to waterlogging. It was disrupted in NSC Bose Road, Anna Pillai Street, Anderson Street, Edappalayam, Cooks Road and Decaster Road in Pulianthope; Sivarajapuram of Choolai section; Baraccah Road in Nammalwarpet; Divan Bashyam Street in Saidapet; and Chari street and Lotus Colony in T. Nagar.In Madhanankuppam, coming under Red Hills section, power supply ws ' > /tmp/suc84s9.txt
sudo echo 'Several residential localities experienced power failure for several hours on Wednesday, when heavy rains pounded the city. Residents in several areas said they experienced intermittent power cuts ranging from two to three hours.The officials of the Tamil Nadu General and Distribution Corporation (Tangedco) said the power cuts were part of precautionary steps taken to avoid any electrical accidents due to waterlogging of roads, trees falling on transformers and snapping of overhead power lines due to gusty winds.Power supply was switched off in parts of south Chennai, covering Nanganallur, Velachery, Madipakkam, Keelkattalai, Pallikaranai, Medavakkam and Tambaram. These areas are predominantly served by overhead power lines and the local EB officials went for a power shutdown from the morning.In several streets of Velachery, covering Ram Nagar, Vijaya Nagar, Balamurugan Nagar, Annai Indira Nagar and Bethel Avenue, power supply was stopped due to waterlogged roads. Also several parts of ECR and OMR, includingaipakkam, went without power supply.K. Ramaswamy, a resident of Maheshwari Avenue in Ullagaram-Puzhithivakkam, complained that the power supply which went off at 2 p.m. had not been restored for over four hours.A senior official of south Chennai said local officials from different sections were deputed to restore power supply even in those roads where rain water stagnated after taking necessary safety precautions.In central and north parts of the city, power supply was switched off by the electricity officials due to waterlogging and tripping of transformers.A senior official of Tangedco said power supply in some core parts of the city was cut off mainly due to waterlogging. It was disrupted in NSC Bose Road, Anna Pillai Street, Anderson Street, Edappalayam, Cooks Road and Decaster Road in Pulianthope; Sivarajapuram of Choolai section; Baraccah Road in Nammalwarpet; Divan Bashyam Street in Saidapet; and Chari street and Lotus Colony in T. Nagar.In Madhanankuppam, coming under Red Hills section, power supply ws ' > /tmp/suc85s9.txt
sudo echo 'Several residential localities experienced power failure for several hours on Wednesday, when heavy rains pounded the city. Residents in several areas said they experienced intermittent power cuts ranging from two to three hours.The officials of the Tamil Nadu General and Distribution Corporation (Tangedco) said the power cuts were part of precautionary steps taken to avoid any electrical accidents due to waterlogging of roads, trees falling on transformers and snapping of overhead power lines due to gusty winds.Power supply was switched off in parts of south Chennai, covering Nanganallur, Velachery, Madipakkam, Keelkattalai, Pallikaranai, Medavakkam and Tambaram. These areas are predominantly served by overhead power lines and the local EB officials went for a power shutdown from the morning.In several streets of Velachery, covering Ram Nagar, Vijaya Nagar, Balamurugan Nagar, Annai Indira Nagar and Bethel Avenue, power supply was stopped due to waterlogged roads. Also several parts of ECR and OMR, includingaipakkam, went without power supply.K. Ramaswamy, a resident of Maheshwari Avenue in Ullagaram-Puzhithivakkam, complained that the power supply which went off at 2 p.m. had not been restored for over four hours.A senior official of south Chennai said local officials from different sections were deputed to restore power supply even in those roads where rain water stagnated after taking necessary safety precautions.In central and north parts of the city, power supply was switched off by the electricity officials due to waterlogging and tripping of transformers.A senior official of Tangedco said power supply in some core parts of the city was cut off mainly due to waterlogging. It was disrupted in NSC Bose Road, Anna Pillai Street, Anderson Street, Edappalayam, Cooks Road and Decaster Road in Pulianthope; Sivarajapuram of Choolai section; Baraccah Road in Nammalwarpet; Divan Bashyam Street in Saidapet; and Chari street and Lotus Colony in T. Nagar.In Madhanankuppam, coming under Red Hills section, power supply ws ' > /tmp/suc86s9.txt
sudo echo 'Several residential localities experienced power failure for several hours on Wednesday, when heavy rains pounded the city. Residents in several areas said they experienced intermittent power cuts ranging from two to three hours.The officials of the Tamil Nadu General and Distribution Corporation (Tangedco) said the power cuts were part of precautionary steps taken to avoid any electrical accidents due to waterlogging of roads, trees falling on transformers and snapping of overhead power lines due to gusty winds.Power supply was switched off in parts of south Chennai, covering Nanganallur, Velachery, Madipakkam, Keelkattalai, Pallikaranai, Medavakkam and Tambaram. These areas are predominantly served by overhead power lines and the local EB officials went for a power shutdown from the morning.In several streets of Velachery, covering Ram Nagar, Vijaya Nagar, Balamurugan Nagar, Annai Indira Nagar and Bethel Avenue, power supply was stopped due to waterlogged roads. Also several parts of ECR and OMR, includingaipakkam, went without power supply.K. Ramaswamy, a resident of Maheshwari Avenue in Ullagaram-Puzhithivakkam, complained that the power supply which went off at 2 p.m. had not been restored for over four hours.A senior official of south Chennai said local officials from different sections were deputed to restore power supply even in those roads where rain water stagnated after taking necessary safety precautions.In central and north parts of the city, power supply was switched off by the electricity officials due to waterlogging and tripping of transformers.A senior official of Tangedco said power supply in some core parts of the city was cut off mainly due to waterlogging. It was disrupted in NSC Bose Road, Anna Pillai Street, Anderson Street, Edappalayam, Cooks Road and Decaster Road in Pulianthope; Sivarajapuram of Choolai section; Baraccah Road in Nammalwarpet; Divan Bashyam Street in Saidapet; and Chari street and Lotus Colony in T. Nagar.In Madhanankuppam, coming under Red Hills section, power supply ws ' > /tmp/suc87s9.txt
